spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather?serverTimezone=Europe/Minsk&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-fauto: validate
  flyway:
    enabled: true
    ignoreMissingMigrations: true
    cleanOnValidationError: true