spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Europe/Minsk&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: testtest
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-fauto: validate
  flyway:
    enabled: true
    ignoreMissingMigrations: true
    cleanOnValidationError: true


blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 999 888 88 88
  email: mail@mail.ru
  copyright: Подкуйко Руслан
  copyrightFrom: 2021
