spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather?serverTimezone=Europe/Minsk&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-fauto: validate
